name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install doctl
        run: |
          curl -fsSL https://github.com/digitalocean/doctl/releases/latest/download/doctl-linux-amd64.tar.gz \
            -o doctl.tar.gz
          sudo tar -xzvf doctl.tar.gz -C /usr/local/bin doctl

      - name: Authenticate doctl
        run: doctl auth init -t "${{ secrets.DIGITALOCEAN_TOKEN }}"

      - name: Ensure SSH key is imported
        run: |
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > /tmp/deploy_key.pub
          FP="${{ secrets.SSH_KEY_FINGERPRINT }}"
          if ! doctl compute ssh-key list --format FingerPrint --no-header | grep -q "$FP"; then
            doctl compute ssh-key import deploy_key \
              --public-key-file /tmp/deploy_key.pub \
              --fingerprint "$FP"
          fi

      - name: Ensure droplet exists
        run: |
          NAME="axialy-main"
          if ! doctl compute droplet list --format Name --no-header | grep -xq "$NAME"; then
            doctl compute droplet create "$NAME" \
              --region nyc3 \
              --image ubuntu-24-04-x64 \
              --size s-1vcpu-1gb \
              --ssh-keys "${{ secrets.SSH_KEY_FINGERPRINT }}" \
              --wait
          fi

      - name: Get droplet IP
        id: get_ip
        run: |
          IP=$(doctl compute droplet list axialy-main \
            --format PublicIPv4 --no-header | head -n1)
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ steps.get_ip.outputs.ip }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            apt-get update && apt-get install -y git
            mkdir -p /var/www/html
            cd /var/www/html
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/Axiamax/axialy-marketing-site .
            fi
