name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install & authenticate doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}
        version: latest

    - name: Ensure SSH key is imported
      env:
        SSH_PUB: ${{ secrets.SSH_PUBLIC_KEY }}
        SSH_FP:  ${{ secrets.SSH_FINGERPRINT }}
      run: |
        # dump public key to a file
        echo "$SSH_PUB" > /tmp/deploy_key.pub

        # import only if fingerprint missing
        if ! doctl compute ssh-key list --format FingerPrint --no-header \
             | grep -q "$SSH_FP"; then
          doctl compute ssh-key import deploy_key \
            --public-key-file /tmp/deploy_key.pub \
            --fingerprint "$SSH_FP"
        else
          echo "SSH key already present"
        fi

    - name: Create droplet if missing
      env:
        SSH_FP:  ${{ secrets.SSH_FINGERPRINT }}
        REGION:  nyc3
        IMAGE:   ubuntu-24-04-x64
        SIZE:    s-1vcpu-1gb
        NAME:    axialy-main
      run: |
        if ! doctl compute droplet list --format Name --no-header \
             | grep -xq "$NAME"; then
          doctl compute droplet create "$NAME" \
            --region "$REGION" \
            --image  "$IMAGE"  \
            --size   "$SIZE"   \
            --ssh-keys "$SSH_FP" \
            --wait
        fi

    - name: Get Droplet IP
      id: get_ip
      run: |
        IP=$(doctl compute droplet list axialy-main \
             --format PublicIPv4 --no-header | head -n1)
        echo "ip=$IP" >> $GITHUB_OUTPUT

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host:       ${{ steps.get_ip.outputs.ip }}
        username:   root
        key:        ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          set -e
          apt-get update
          apt-get install -y git
          mkdir -p /var/www/html
          cd /var/www/html
          if [ -d .git ]; then
            git pull
          else
            git clone https://github.com/Axiamax/axialy-marketing-site .
          fi
