name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Droplet settings
      DROPLET: axialy-main
      REGION: nyc3
      IMAGE: ubuntu-24-04-x64
      SIZE: s-1vcpu-1gb

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        run: |
          curl -sL "https://github.com/digitalocean/doctl/releases/latest/download/doctl-$(uname | tr '[:upper:]' '[:lower:]')-amd64.tar.gz" \
            | tar -xzC /usr/local/bin doctl
          doctl version

      - name: Provision (or fetch) Droplet
        id: provision
        run: |
          # Authenticate with DO_TOKEN secret
          doctl auth init -t "${{ secrets.DO_TOKEN }}"

          # Import your SSH public key (idempotent)
          ssh-keygen -y -f <(echo "${{ secrets.SSH_PRIVATE_KEY }}") | \
            doctl compute ssh-key import deploy_key \
              --public-key - \
              --fingerprint "${{ secrets.SSH_FINGERPRINT }}" || true

          # Create droplet if it doesn't exist
          if ! doctl compute droplet get "$DROPLET" >/dev/null 2>&1; then
            doctl compute droplet create "$DROPLET" \
              --region "$REGION" \
              --image "$IMAGE" \
              --size "$SIZE" \
              --ssh-keys "${{ secrets.SSH_FINGERPRINT }}" \
              --wait
          fi

          # Grab its public IP
          IP=$(doctl compute droplet get "$DROPLET" --format PublicIPv4 --no-header)
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ steps.provision.outputs.ip }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            apt-get update && apt-get install -y git
            mkdir -p /var/www/html
            cd /var/www/html
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/Axiamax/axialy-marketing-site .
            fi
