name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      DROPLET: axialy-main
      REGION:  nyc3
      IMAGE:   ubuntu-24-04-x64
      SIZE:    s-1vcpu-1gb

    steps:
      - uses: actions/checkout@v3

      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Ensure SSH key is imported
        run: |
          PUB=$(echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-keygen -y -f -)
          if ! doctl compute ssh-key list --format Fingerprint --no-header \
               | grep -q "${{ secrets.SSH_FINGERPRINT }}"; then
            echo "$PUB" \
              | doctl compute ssh-key import deploy_key \
                --public-key - \
                --fingerprint "${{ secrets.SSH_FINGERPRINT }}"
          fi

      - name: Create or fetch Droplet
        id: provision
        run: |
          if ! doctl compute droplet get "$DROPLET" >/dev/null 2>&1; then
            doctl compute droplet create "$DROPLET" \
              --region "$REGION" \
              --image "$IMAGE" \
              --size "$SIZE" \
              --ssh-keys "${{ secrets.SSH_FINGERPRINT }}" \
              --wait
          fi
          IP=$(doctl compute droplet get "$DROPLET" --format PublicIPv4 --no-header)
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:        ${{ steps.provision.outputs.ip }}
          username:    root
          key:         ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase:  ${{ secrets.SSH_PASSPHRASE }}
          script: |
            apt-get update && apt-get install -y git
            mkdir -p /var/www/html
            cd /var/www/html
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/Axiamax/axialy-marketing-site .
            fi
